# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM1
    frame_id: gps
    config_on_startup: true
    uart1:
      baudrate: 115200
    uart2: 
      baudrate: 115200
    usb:
      baudrate: 115200

    rate: 20.0

    tmode3: 0
    
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
